"""empty message

Revision ID: f9f6e68d08c8
Revises: 
Create Date: 2022-05-14 14:11:56.672367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9f6e68d08c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phrase',
    sa.Column('phrase_id', sa.Integer(), nullable=False),
    sa.Column('ru', sa.String(length=300), nullable=True),
    sa.Column('khanty', sa.String(length=300), nullable=True),
    sa.Column('khanty_cyr', sa.String(length=300), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('phrase_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phrase')
    # ### end Alembic commands ###
